categories: 
- Sequence Analysis
description: SNAP is a general purpose gene finding program suitable for both eukaryotic
    and prokaryotic genomes. SNAP is an acroynm for Semi-HMM-based Nucleic Acid
    Parser.
name: snap
owner: yating-l
